### ISSUE TITLE
Issue in slitherinenv.py

### ISSUE THREAD

**Issue by kimbring2** [bhairavmehta95/slitherin-gym#2]
Hello, writer.

I tried to insert output of slitherin env into MLP policy network and found some issue from that trial.

First is that reset function do not return observation.

```
def reset(self):
        #print("def reset(self):")
        for i, p in enumerate(self.agents):
            self.killed[i] = False

            x = np.random.randint(1, self.max_spawn_idx - 1) * self.spacing
            y = np.random.randint(1, self.max_spawn_idx - 1) * self.spacing
            direction = np.random.randint(0, 1) # TODO: Fix vertical spawning

            p._reset(x, y, direction)

        for f in range(self.num_fruits):
            self.fruits[f] = self._generate_goal()

        self.active_agents = self.num_agents
        new_obs = []

        '''
        for i in range(self.num_agents):
            ob = self._generate_obs(i)
            new_obs.append(ob)   		
  
        return deepcopy(new_obs)
        '''
```

Second is that format of observation_space and action_space is not same.
```
       self.observation_space = spaces.Box(low=-1, high=3, 
       #                                    shape=(self.num_agents, self.window_dimension // self.spacing, self.window_dimension // self.spacing))

       '''
        self.observation_space = spaces.Tuple(
            [spaces.Discrete((self.window_dimension // self.spacing) * (self.window_dimension // self.spacing)) for i in range(self.num_agents)]
        )
       '''

        self.action_space = spaces.Tuple(
            [spaces.Discrete(4) for i in range(self.num_agents)]
        )
```

Also, I am little confused with Box and Discrete class of gym. Is it possible to insert 2D Box value into placeholder of tensorflow? 
Should flatten function be used for observation value?

Thank you for your work.

**Comment by bhairavmehta95** [comment]
Hi @kimbring2 , thank you for your diligent testing.

I have fixed the first issue that you've brought up, and your second comment brings up a valid point.
Currently, there are not a lot of open source algorithms for multiple agent environments; in my own work, I usually end up having to rewrite some part of the code (i.e openai's baselines, especially the vectorized environment parts). Ideally, you could flatten and split the observation space and feed them in as if they were two different timesteps, and accumulate the actions as well.

**Comment by kimbring2** [comment]
Hello, bhairavmehta95.

I understand your reply about of environment.

Recently, I am trying to integrate Alpha Zero self-play algorithm with the
slitherin env.
Luckly, there is already reference code which is based on Othello game.

After integration is completed, I wish to debate about that code.

Thank you.

2018-03-05 14:49 GMT+09:00 Bhairav Mehta <notifications@github.com>:
